### ISSUE TITLE
unexpected token {

### ISSUE THREAD

**Issue by ofqwx** [caseyWebb/vultr-pingtest#1] opened 2017-08-17 12:43 UTC
Hi, first of all great job!. I installed the package but I can't make it work around, I get unexpected token { error at index.js.

**Comment by caseyWebb** [comment] 2017-08-17 19:17
What version of Node are you using?

**Comment by caseyWebb** [comment] 2018-01-28 16:53
Closing under the assumption this is caused by an outdated version of node

**Closed by caseyWebb** 2018-01-28 16:53 UTC
